name: basic_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-198.0.dev <4.0.0'



dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/img/profile_pic1.jpg
    - assets/img/profile_pic2.jpg
    - assets/img/profile_pic3.jpg
    - assets/img/profile_pic4.jpg
    - assets/img/place1.jpg
    - assets/img/place2.jpg
    - assets/img/place3.jpg


